version: '3'

services:
  postgres:
    container_name: db_biblioteca_elo_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuserElo
      POSTGRES_PASSWORD: myPasswordElo
      POSTGRES_DB: db_biblioteca_elo
    ports:
      - "25432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadmin_biblioteca_elo
    image: dpage/pgadmin4:7.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "elotech.biblioteca@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "elotech"
    ports:
      - "26543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge